config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients/clients#index"
  scope module: 'clients' do
    resources :clients do
      resources :addresses
      resources :phone_numbers
      resources :identifications
      resources :employments
      resources :family_members
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :office
  belongs_to :user
  has_many :client_proposals
  has_one :alias
  has_many :phone_numbers
  has_many :addresses
  has_many :identifications
  has_many :employments
  has_many :family_members
  has_many :businesses
  has_many :business_debts, through: :businesses
  has_many :employment_insurance_claims
  has_many :notes

  enum gender:{ male: "male", female: "female" }
  enum marital_status:{ single: "single", married: "married", common_law: "comman-law", separated: "separated", divorced: "divoreced" }
end

app/models/identification.rb
class Identification < ApplicationRecord
  belongs_to :client

  enum id_type:{ drivers_license: "drivers_license", sin: "sin" }
end

app/controllers/clients/addresses_controller.rb
class Clients::AddressesController < ApplicationController

  def index
    @client = Client.find(params[:client_id])
    @addresses = @client.addresses.order(:address_type)
    @breadcrumbs = { Clients: clients_path, "#{@client.first_name} #{@client.last_name}": @client }
  end

  def new
    @address = Client.find(params[:client_id]).addresses.build
    @path = client_addresses_path(@address.client)
    render partial: 'form', address: @address, path: @path
  end

  def edit
    @address = Address.find(params[:id])
    @path = client_address_path(@address.client, @address)
    render partial: 'form', address: @address, path: @path
  end

  def create
    @client = Client.find(params[:client_id])
    @address = @client.addresses.build(address_params)
    if params[:current_address]
      @address.address_type = :current
    else
      @address.address_type = :past
    end
    turbo_stream if @address.save
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      render partial: 'address', locals: { address: @address }
    end
  end

  def destroy
    @address = Address.find(params[:id])
    if @address.destroy
      turbo_stream
    end
  end

  private
  def address_params
    params.require(:address).permit(:address_1, :address_2, :city, :province, :postal_code, :address_type, :current_address)
  end

end

app/controllers/clients/clients_controller.rb
class Clients::ClientsController < ApplicationController
  def index
    @clients = Client.all
    @breadcrumbs = { Clients: nil }
  end

  def show
    @client = Client.find(params[:id])
    @breadcrumbs = { Clients: clients_path, "Client Details": nil }
  end

  def edit
    @client = Client.find(params[:id])
    render partial: "#{params[:field]}_field", client: @client
  end

  def update
    @client = Client.find(params[:id])
    @client.update(client_params)
    render partial: params[:client][:field], client: @client
  end

  private
  def client_params
    params.require(:client).permit(:first_name, :last_name, :middle_initial, :email, :date_of_birth, :gender, :marital_status, :family_size)
  end
end

app/controllers/clients/employments_controller.rb
class Clients::EmploymentsController < ApplicationController

  def index
    @client = Client.find(params[:client_id])
    @employments = @client.employments
    @breadcrumbs = { Clients: clients_path, "#{@client.first_name} #{@client.last_name}": @client }
  end

  def new
    @client = Client.find(params[:client_id])
    @employment = @client.employments.build
    @path = client_employments_path(@client)
    render partial: 'form', employment: @employment, path: @path
  end

  def edit
    @client = Client.find(params[:client_id])
    @employment = Employment.find(params[:id])
    @path = client_employment_path(@client, @employment)
    render partial: 'form', employment: @employment, path: @path
  end

  def create
    @client = Client.find(params[:client_id])
    @employment = @client.employments.build(employment_params)
    turbo_stream if @employment.save
  end

  def update
    @employment = Employment.find(params[:id])
    if @employment.update(employment_params)
      render partial: 'employment', locals: { employment: @employment }
    end
  end

  def destroy
    @employment = Employment.find(params[:id])
    if @employment.destroy
      turbo_stream
    end
  end

  private
  def employment_params
    params.require(:employment).permit(:employer, :employment_type, :address_1, :address_2, :city, :province, :position, :start_date, :end_date, :current)
  end

end

app/controllers/clients/family_members_controller.rb
class Clients::FamilyMembersController < ApplicationController

  def index
    @client = Client.find(params[:client_id])
    @family_members = @client.family_members
    @breadcrumbs = { Clients: clients_path, "#{@client.first_name} #{@client.last_name}": @client }
  end

  def new
    @client = Client.find(params[:client_id])
    @family_member = @client.family_members.build
    @path = client_family_members_path(@client)
    render partial: 'form', family_member: @family_member, path: @path
  end

  def edit
    @client = Client.find(params[:client_id])
    @family_member = FamilyMember.find(params[:id])
    @path = client_family_member_path(@client, @family_member)
    render partial: 'form', family_member: @family_member, path: @path
  end

  def create
    @client = Client.find(params[:client_id])
    @family_member = @client.family_members.build(family_member_params)
    turbo_stream if @family_member.save
  end

  def update
    @family_member = FamilyMember.find(params[:id])
    if @family_member.update(family_member_params)
      render partial: 'family_member', locals: { family_member: @family_member }
    end
  end

  def destroy
    @family_member = FamilyMember.find(params[:id])
    if @family_member.destroy
      turbo_stream
    end
  end

  private
  def family_member_params
    params.require(:family_member).permit(:first_name, :last_name, :relationship, :address_1, :address_2, :city, :province, :postal_code, :date_of_birth, :income)
  end

end

app/controllers/clients/identifications_controller.rb
class Clients::IdentificationsController < ApplicationController

  def index
    @client = Client.find(params[:client_id])
    @identifications = @client.identifications
    @breadcrumbs = { Clients: clients_path, "#{@client.first_name} #{@client.last_name}": @client }
  end

  def new
    @identification = Client.find(params[:client_id]).identifications.build
    @path = client_identifications_path(@identification.client)
    render partial: 'form', identification: @identification, path: @path
  end

  def edit
    @client = Client.find(params[:client_id])
    @identification = Identification.find(params[:id])
    @path = client_identification_path(@identification.client, @identification)
    render partial: 'form', identification: @identification, path: @path
  end

  def create
    @client = Client.find(params[:client_id])
    @identification = @client.identifications.build(identification_params)
    turbo_stream if @identification.save
  end

  def update
    @identification = Identification.find(params[:id])
    if @identification.update(identification_params)
      render partial: 'identification', locals: { identification: @identification }
    end
  end

  def destroy
    @identification = Identification.find(params[:id])
    if @identification.destroy
      turbo_stream
    end
  end

  private
  def identification_params
    params.require(:identification).permit(:id_type, :number, :expiry_date)
  end

end

app/controllers/clients/phone_numbers_controller.rb
class Clients::PhoneNumbersController < ApplicationController
  def index
    @client = Client.find(params[:client_id])
    @phone_numbers = @client.phone_numbers
    @breadcrumbs = { Clients: clients_path, "#{@client.first_name} #{@client.last_name}": @client }
  end

  def edit
    @phone_number = PhoneNumber.find(params[:id])
    @path = client_phone_number_path(@phone_number.client, @phone_number)
    render partial: 'form', phone_number: @phone_number, path: @path
  end

  def show
    @phone_number = PhoneNumber.find(params[:id])
    render 'show', phone_number: @phone_number
  end

  def new
    @phone_number = Client.find(params[:client_id]).phone_numbers.build
    @path = client_phone_numbers_path(@phone_number.client)
    render partial: 'form', phone_number: @phone_number, path: @path
  end

  def create
    @client = Client.find(params[:client_id])
    @phone_number = @client.phone_numbers.build(phone_number_params)
    turbo_stream if @phone_number.save
  end

  def update
    @phone_number = PhoneNumber.find(params[:id])
    if @phone_number.update(phone_number_params)
      render partial: 'phone_number', locals: { phone_number: @phone_number }
    end
  end

  def destroy
    @phone_number = PhoneNumber.find(params[:id])
    if @phone_number.destroy
      turbo_stream
    end
  end

  private
  def phone_number_params
    params.require(:phone_number).permit(:number, :number_type)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.all
    @breadcrumbs = { Clients: nil }
  end

  def show
    @client = Client.find(params[:id])
    @breadcrumbs = { Clients: clients_path, "Client Details": nil }
  end
end

app/helpers/clients/addresses_helper.rb
module Clients::AddressesHelper
end

app/helpers/clients/clients_helper.rb
module Clients::ClientsHelper
end

app/helpers/clients/employments_helper.rb
module Clients::EmploymentsHelper
end

app/helpers/clients/family_members_helper.rb
module Clients::FamilyMembersHelper
end

app/helpers/clients/identifications_helper.rb
module Clients::IdentificationsHelper
end

app/helpers/clients/phone_numbers_helper.rb
module Clients::PhoneNumbersHelper
end

app/views/clients/identifications/_form.html+turbo_frame.erb
<%= turbo_frame_tag @identification do %>
  <div class="bg-white border border-slate-300 rounded py-2 px-4 mb-4">
    <%= form_with model: @identification, url: @path do |form| %>
    <div class="my-2">
      <p><label>Type</label></p>
      <%= form.select :id_type, [["Driver's License", :drivers_license], ["SIN", :sin]], {}, class: "border border-slate-300 rounded w-full" %>
    </div>
    <div class="my-2">
      <p><label>Number</label></p>
      <%= form.text_field :number, class: "border border-slate-300 rounded w-full" %>
    </div>
    <div class="my-2">
      <p><label>Expiry Date</label></p>
      <%= form.date_select :expiry_date, {}, class: "border border-slate-300 rounded" %>
    </div>
    <div class="mt-4 mb-2">
      <%= form.submit "Save", class: "text-sm border bg-green-100 text-green-700 border border-green-600 rounded py-2 px-3" %>
      <%= "Cancel" %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/clients/identifications/_form.html.erb
<%= turbo_frame_tag @identification do %>
  <div class="bg-white border border-slate-300 rounded py-2 px-4 mb-4">
    <%= form_with model: @identification, url: @path do |form| %>
    <div class="my-2">
      <p><label>Type</label></p>
      <%= form.select :id_type, [["Driver's License", :drivers_license], ["SIN", :sin]], {}, class: "border border-slate-300 rounded w-full" %>
    </div>
    <div class="my-2">
      <p><label>Number</label></p>
      <%= form.text_field :number, class: "border border-slate-300 rounded w-full" %>
    </div>
    <div class="my-2">
      <p><label>Expiry Date</label></p>
      <%= form.date_select :expiry_date, {}, class: "border border-slate-300 rounded" %>
    </div>
    <div class="mt-4 mb-2">
      <%= form.submit "Save", class: "text-sm border bg-green-100 text-green-700 border border-green-600 rounded py-2 px-3" %>
      <%= "Cancel" %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/clients/identifications/_identification.html.erb
<%= turbo_frame_tag identification do %>
  <div class="bg-white border border-slate-300 rounded mb-4 overflow-hidden">
    <div class="flex py-2 px-3">
      <div class="grow">
        <p><%= identification.id_type.to_s.titleize %></p>
        <p><%= identification.number %></p>
        <p><%= identification.expiry_date %></p>
      </div>
      <div class="flex gap-2 items-start">
        <%= link_to 'Edit', edit_client_identification_path(identification.client, identification), class: "text-sm border border-slate-300 hover:border-slate-400 text-slate-500 rounded py-2 px-3" %>
        <%= link_to "Delete", client_identification_path(identification.client, identification), class: "text-sm border border-slate-300 hover:border-slate-400 text-slate-500 rounded py-2 px-3 block", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete identification?" } %>
      </div>
    </div>
  </div>
<% end %>

app/views/clients/identifications/create.turbo_stream.erb
<%= turbo_stream.append 'identifications' do %>
  <%= render partial: 'identification', locals: { identification: @identification } %>
<% end %>

<%= turbo_stream.update 'new_identification' do %>
  <div class="bg-white border border-slate-300 rounded py-2 px-4 mb-4">
    <%= link_to 'Add Identification', new_client_identification_path(@client) %>
  </div>
<% end %>

app/views/clients/identifications/destroy.turbo_stream.erb
<%= turbo_stream.remove @identification do %>
<% end %>

app/views/clients/identifications/index.html.erb
<%= render partial: 'layouts/breadcrumbs', locals: { breadcrumbs: @breadcrumbs } %>

<h1 class="font-bold text-2xl mb-4">Identification</h1>
<div class="grid grid-cols-5 gap-4">
  <div class="col-span-4">
    <%= turbo_frame_tag 'new_identification' do %>
      <%= link_to 'Add Identification', new_client_identification_path(@client), class: "bg-white border border-slate-300 rounded py-2 px-4 mb-4 text-sm block" %>
    <% end  %>
    <%= turbo_frame_tag 'identifications' do %>
      <%= render @identifications %>
    <% end %>
  </div>
  <%= render partial: "clients/clients/proposal_status" %>
</div>